server:
  port: 8081
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
    enabled-by-default: true
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: SHREE579108
  jpa:
    show-sql: true
